language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: 8
    - node_js: 10
    - node_js: 11
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
